[k8s]
localhost ansible_connection=local

[pihole_servers]
10.0.0.13 ansible_user=ansible-deploy

[webmin_servers]
10.0.0.13 webmin_user=ansible_deploy

[docker_servers]
10.0.0.12 ansible_user=ansible-deploy
